### PR TITLE
Revamp tags page

### LINKED ISSUE #140: Tags index page needs a revamp

### PR DESCRIPTION
**Pull request by wkenned1**
Resolves #140 

- [x] Prettify
- [x] De-duplicate
- [x] Scrunch them up closer
- [x] Update ArticleTag component
- [x] Use ArticleTag component in tags page and article preview

### CODE REVIEW

**Comment by andreilgeorgescu** [comment]
Resolves #140

**Review by andreilgeorgescu — CHANGES_REQUESTED** [review]
The tags need to be scrunched up much closer

**Comment by wkenned1** [comment]
> The tags need to be scrunched up much closer

Horizontally or vertically? There is minimal spacing between them horizontally.

**Comment by wkenned1** [comment]
image

I reduced the vertical spacing to condense them.

**Review by andreilgeorgescu — APPROVED** [review]

**Pull request merged**
