### PR TITLE
Format

### PR DESCRIPTION
**Pull request by andreilgeorgescu**

### CODE REVIEW

**Comment by daniel-ciocirlan** [comment]
@andreilgeorgescu what happened to this one?

**Comment by andreilgeorgescu** [comment]
> @andreilgeorgescu what happened to this one?

The latest article and new tag don't seem like they were fully formatted when submitted. Also the associated images weren't compressed.

I can make a PR GitHub Action to verify formatting and linting.

**Comment by daniel-ciocirlan** [comment]
Understood. Do we need to downscale the images?

**Comment by andreilgeorgescu** [comment]
> Understood. Do we need to downscale the images?

No, they just need to be losslessly compressed with [oxipng](https://trunk.io/formatters/optimization/oxipng) which Trunk should be doing automatically.

**Comment by daniel-ciocirlan** [comment]
Any blockers on this one? For the png conflicts - we can safely replace them with the files in this PR

**Review by wkenned1 — APPROVED** [review]

**Pull request merged**
