### PR TITLE
Featured bundle should be centered when vertical

### LINKED ISSUE #161: Featured bundle should be centered when vertical

### PR DESCRIPTION
**Pull request by andreilgeorgescu**
Resolves #161

### CODE REVIEW

**Comment by andreilgeorgescu** [comment]
@daniel-ciocirlan the build broke on this as well but everything seems to pass locally. What do the CloudFlare logs say?

**Comment by daniel-ciocirlan** [comment]
@andreilgeorgescu it makes little sense to me:

```
2024-12-08T18:16:37.905077Z	Cloning repository...
2024-12-08T18:16:38.759352Z	From https://github.com/rockthejvm/rockthejvm-site
2024-12-08T18:16:38.759821Z	 * branch            75c30009ce6094134419d833202fb58f4d60e8f8 -> FETCH_HEAD
2024-12-08T18:16:38.760024Z	
2024-12-08T18:16:44.867066Z	HEAD is now at 75c3000 Featured bundle should be centered when vertical
2024-12-08T18:16:44.867549Z	Encountered 3 file(s) that should have been pointers, but weren't:
2024-12-08T18:16:44.867681Z		src/content/articles/structured-concurrency-in-java/images/parent-child.png
2024-12-08T18:16:44.867821Z		src/content/articles/structured-concurrency-in-java/images/sc-sequence.png
2024-12-08T18:16:44.867944Z		src/content/articles/structured-concurrency-in-java/images/structured-concurrency.png
2024-12-08T18:16:44.868054Z	
2024-12-08T18:16:44.942354Z	
2024-12-08T18:16:44.942765Z	Using v2 root directory strategy
2024-12-08T18:16:44.966877Z	Success: Finished cloning repository files
2024-12-08T18:16:46.431451Z	Checking for configuration in a wrangler.toml configuration file (BETA)
2024-12-08T18:16:46.432346Z	
2024-12-08T18:16:46.525874Z	No wrangler.toml file found. Continuing.
2024-12-08T18:16:46.665828Z	Detected the following tools from environment: pnpm@8.7.1, nodejs@18.17.1
2024-12-08T18:16:47.433473Z	Installing project dependencies: pnpm install
2024-12-08T18:16:48.111105Z	 WARN  Ignoring not compatible lockfile at /opt/buildhome/repo/pnpm-lock.yaml
2024-12-08T18:16:48.305371Z	Progress: resolved 1, reused 0, downloaded 0, added 0
2024-12-08T18:16:48.315989Z	 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/eslint-plugin-mdx: Not Found - 404
2024-12-08T18:16:48.316658Z	
2024-12-08T18:16:48.317019Z	This error happened while installing a direct dependency of /opt/buildhome/repo
2024-12-08T18:16:48.317143Z	
2024-12-08T18:16:48.317617Z	eslint-plugin-mdx is not in the npm registry, or you have no permission to fetch it.
2024-12-08T18:16:48.317731Z	
2024-12-08T18:16:48.318222Z	No authorization header was set for the request.
2024-12-08T18:16:48.388513Z	Error: Exit with error code: 1
2024-12-08T18:16:48.388773Z	    at ChildProcess.<anonymous> (/snapshot/dist/run-build.js)
2024-12-08T18:16:48.388886Z	    at Object.onceWrapper (node:events:652:26)
2024-12-08T18:16:48.389008Z	    at ChildProcess.emit (node:events:537:28)
2024-12-08T18:16:48.389112Z	    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
2024-12-08T18:16:48.399487Z	Failed: build command exited with code: 1
2024-12-08T18:16:49.088891Z	Failed: error occurred while running build command
```

**Comment by andreilgeorgescu** [comment]
> @andreilgeorgescu it makes little sense to me:

That's a lot of issues. I think the build just had a hiccup. Can you try rebuilding it on your end?

**Comment by daniel-ciocirlan** [comment]
The build works now

**Review by wkenned1 — APPROVED** [review]

**Pull request merged**
